ahr-runtime-ctl: install-profile action

diff --git a/bin/ahr-runtime-ctl b/bin/ahr-runtime-ctl
--- a/bin/ahr-runtime-ctl
+++ b/bin/ahr-runtime-ctl
@@ -19,8 +19,10 @@ function show_help(){
     echo "Examples:"
     echo "    ahr-runtime-ctl template \$AHR_HOME/templates/overrides-large-template.yaml"
     echo ""
+    echo "    ahr-runtime-ctl install-profile <project> <profile-name>"
     echo ""
     echo "    ahr-runtime-ctl apigeectl <apigeectl-command-line-arguments>"
+    echo ""
     echo "    ahr-runtime-ctl apigeectl wait-for-ready <other-arguments-like-f-and-c>."
     echo ""
     echo "    ahr-runtime-ctl setsync <sa-email or \"\" to reset>"
@@ -349,6 +351,105 @@ curl -H "Authorization: Bearer $(token)" -H "Content-Type: application/json" htt
   "environment": "$ENV"
 }
 EOT
+
+
+#-----------------------------------------------------------------------
+elif [ "install-profile" == "$ACTION" ]; then
+    if [ "$#" -lt 3 ]; then
+        echo "ERROR: Either project or profile or both are not provided."
+        echo ""
+        echo "    ahr-runtime-ctl install-profile <project> <profile>"
+        echo ""
+        echo "Example:"
+        echo "    ahr-runtime-ctl install-profile \$GOOGLE_CLOUD_PROJECT small"
+        echo ""
+        echo "Supported profiles: small"
+        echo ""
+        echo "Override if you wish (ie, set up before calling the operation):"
+        echo "    REGION ZONE AX_REGION"
+        echo "    MACHINE_TYPE_DATA MACHINE_TYPE_RUNTIME"
+        exit 5
+    fi
+    PROJECT=$2
+    PROFILE=$3
+
+    check_envvars "AHR_HOME"
+
+# 
+# profile: small
+# 
+
+
+
+## Hybrid Install Environment
+
+export HYBRID_HOME=~/apigee-hybrid-install
+export HYBRID_ENV=$HYBRID_HOME/hybrid-130.env
+
+mkdir -p $HYBRID_HOME
+
+cp $AHR_HOME/examples/hybrid-sz-s-1.3.0.sh $HYBRID_ENV
+
+echo "Using Project: $PROJECT"
+
+gcloud config set project $PROJECT
+
+source <(grep 'export REGION=' $HYBRID_ENV)
+
+ahr-verify-ctl api-enable
+
+# Provision Load Balancer
+gcloud compute addresses create runtime-ip --region $REGION
+
+source $HYBRID_ENV
+
+# Create GKE cluster
+ahr-cluster-ctl template $CLUSTER_TEMPLATE > $CLUSTER_CONFIG
+
+ahr-cluster-ctl create
+
+# Install Certificate Manager
+kubectl apply --validate=false -f $CERT_MANAGER_MANIFEST
+
+
+# Install ASM
+ahr-cluster-ctl asm-get
+
+export ASM_HOME=$HYBRID_HOME/istio-1.5.8-asm.7
+export PATH=$ASM_HOME/bin:$PATH
+
+ahr-cluster-ctl template $ASM_TEMPLATE > $ASM_CONFIG
+istioctl manifest apply -f $ASM_CONFIG
+
+# Install Hybrid runtime
+ahr-runtime-ctl get
+
+export APIGEECTL_HOME=$HYBRID_HOME/apigeectl_1.3.0-c9606a3_linux_64
+export PATH=$APIGEECTL_HOME:$PATH
+
+source $AHR_HOME/bin/ahr-lib.sh
+ahr-runtime-ctl org-validate-name $ORG
+ahr-runtime-ctl org-create $ORG --ax-region $AX_REGION
+ahr-runtime-ctl env-create $ENV
+ahr-runtime-ctl env-group-create $ENV_GROUP $RUNTIME_HOST_ALIAS
+ahr-runtime-ctl env-group-assign $ORG $ENV_GROUP $ENV
+
+ahr-sa-ctl create all
+
+ahr-runtime-ctl setsync $SYNCHRONIZER_SA_ID
+
+ahr-verify-ctl cert-create-ssc $RUNTIME_SSL_CERT $RUNTIME_SSL_KEY $RUNTIME_HOST_ALIAS
+
+gcloud projects add-iam-policy-binding $PROJECT --member $(get_account_as_member) --role roles/apigee.admin
+
+ahr-runtime-ctl template $AHR_HOME/templates/overrides-small-130-template.yaml > $RUNTIME_CONFIG
+
+ahr-runtime-ctl apigeectl init -f $RUNTIME_CONFIG
+ahr-runtime-ctl apigeectl wait-for-ready -f $RUNTIME_CONFIG
+
+ahr-runtime-ctl apigeectl apply -f $RUNTIME_CONFIG
+ahr-runtime-ctl apigeectl wait-for-ready -f $RUNTIME_CONFIG
+
 
 #-----------------------------------------------------------------------
 else
